### ISSUE TITLE
OAuth2 client secret is not set for prod

### ISSUE THREAD

**Issue by jshslsky** [universityofcalifornia/chef-ectg-ucnext#5]
I manually added the secret to production.yml for now, but before I made the change there was no value set for the secret.

**Comment by stevenolen** [comment]
fixed in upstream: https://github.com/universityofcalifornia/chef-ucnext/commit/b0c683f8df4755b5b58457f351b26fbf5b58de6e

The upstream had two template files for the same resource that diverged.  as far as i can see, the host-specific one for `ucnext.org` was just cruft from an earlier release of the resource...it follows the standard file now.
